name: retail_sales_elt
version: '1.0'
config-version: 2
profile: retail_sales_elt
model-paths: ["models"]
source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
models:
  retail_sales_elt:
    +materialized: table
    silver:
      +database: silver
      +schema: silver
    gold:
      +database: gold
      +schema: gold
